
# Wait x milliseconds for starship to check files under the current directory.
command_timeout = 1111
scan_timeout = 1000

[line_break]
# disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Dotfiles" = "Â°Â°Â°"
"~/DOTS" = "Â°Â°Â°"
"global" = "ğŸŒ"
"nixos" = "â„ï¸ "

[package]
disabled = true

[cmd_duration]
min_time = 1000
show_notifications = true

[time]
# disabled = true
format = 'ğŸ•™[ $time ]($style)'
time_format = "%H:%M"
utc_time_offset = "-5"
time_range = '22:00:00-07:00:00'

[shell]
disabled = true

[status]
# disabled = true
symbol = "ğŸ”´"
format = '[$symbol $common_meaning$signal_name$maybe_int]($style) '
map_symbol = true

[character]
success_symbol = "ğŸš€"
error_symbol = "ğŸš©"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
allow_windows = true
# disabled = true

[git_status]
# disabled = true
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
