# Craole_Lite

spacing         = 2
padding         = 0
separator       = ""
key_color       = "green"
separator_color = "gray"

[custom_ascii]
path  = "~/.config/macchina/images/smile.ascii"
color = "green"

[palette]
type            = "Light"
glyph           = " ● "
visible         = false

[bar]
glyph           = "ߋ"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
title           = " Craole "
border          = "rounded"
visible         = false

[box.inner_margin]
x               = 2
y               = 0

[randomize]
# key_color       = true
separator_color = true
pool = "indexed"


[keys]
host            = "  "
kernel          = "  "
battery         = "  "
os              = "  "
de              = "  "
wm              = " 拓 "
distro          = "  "
terminal        = "  "
shell           = "  "
packages        = "  "
uptime          = "  "
memory          = "  "
machine         = "  "
local_ip        = "  "
backlight       = "  "
resolution      = "  "
cpu_load        = "  "
cpu             = "  "
