# Craole

spacing = 0
padding = 1
hide_ascii = false
prefer_small_ascii = false
separator = " | "
key_color = "Green"
separator_color = "Green"

[custom_ascii]
path = "~/.config/macchina/images/terminal.ascii"
color = "Green"

[palette]
type = "Light"
visible = true
glyph = " ❇ "

[bar]
glyph = "■"
symbol_open = '['
symbol_close = ']'
hide_delimiters = false
visible = false

[box]
title = " Craole "
border = "plain"
visible = false

[box.inner_margin]
x = 2
y = 1

[randomize]
# key_color = false
separator_color = false
pool = "hexadecimal"

[keys]
host = "          Host | "
kernel = "        Kernel | "
battery = "       Battery | "
os = "            OS | "
de = "   Desktop Env | "
wm = "Window Manager | 拓"
distro = "  Distribution | "
terminal = "      Terminal | "
shell = "         Shell | "
packages = "      Packages | "
uptime = "        Uptime | "
memory = "        Memory | "
machine = "       Machine | "
local_ip = "    IP Address | "
backlight = "    Brightness | "
resolution = "    Resolution | "
cpu_load = "      CPU Load | "
cpu = "           CPU | "
