interface = "wlan0"
long_uptime = false
long_shell = false
long_kernel = true
current_shell = false
physical_cores = true
theme = "Craole_Lite"
# theme = "/storage/DOTS/Config/cli/macchina/themes/Craole_Lite.toml"
show = [
  # "Host",
  # "Machine",
  # "Processor",
  # "Distribution",
  # "OperatingSystem",
  # "Kernel",
  # "Resolution",
  # "DesktopEnvironment",
  # "WindowManager",
  "Backlight",
  "Packages",
  # "Terminal",
  "Shell",
  # "LocalIP",
  # "Uptime",
  # "ProcessorLoad",
  "Memory",
  "Battery",
]
